from alibabacloud_ecs20140526.client import Client
from alibabacloud_tea_openapi.models import Config
from alibabacloud_ecs20140526.models import DescribeSnapshotsRequest
from alibabacloud_tea_openapi.exceptions import ClientException
